# Generated by Django 5.0.3 on 2024-03-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='genero',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
